[build-system]
## I want to use setuptools 'build' backend
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pup_py"
version = "0.1.0"
# authors = [{name = "developer-1v", email = "Developer-1v@proton.me"}] ## NOTE: I original had this, which is supposed to be correct, but it won't work with current setuptools 
authors = [{name = "developer-1v"}, {email = "Developer-1v@proton.me"}]
maintainers = [{name = "developer-1v"}, {email = "developer-1v@gmail.com"}]
license = {text = "MIT License"}
description = """ Homepage: https://github.com/developer-1v/pup_py\n\nCreates a package from a source and then automatically tests the package, uploads to PyPI, and installs to your PC"""
keywords = [
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.11",
]
requires-python = ">=3.6"
dependencies = [
# "Print_Tricks_And_More_Alpha==0.3.179.9929",
]

[project.readme]
text = "Generic Readme for a package"
content-type = "text/plain"

[project.urls]
Homepage = "https://github.com/developer-1v/pup_py"
Source = "https://github.com/developer-1v/pup_py"
Tracker = "https://github.com/developer-1v/pup_py/issues"
PyPI = "https://pypi.org/project/pup_py/"

[project.scripts]
# pup_py = "pup_py.cli:main"

[project.optional-dependencies]
testing = ["pytest>=3"]

[tool.setuptools]
zip-safe = false
include-package-data = true
packages = { find = { where = [".."], include = ["."] } }