[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "A"
version = "0.1.0"

[tool.setuptools]
include-package-data = true
zip-safe = false
packages = { find = { where = ["."] } }